

void test_main(void) {

    extern int test_aes(void);
    test_aes();
    extern int test_array(void);
    test_array();
    extern int test_binary_search(void);
    test_binary_search();
    extern int test_checksum(void);
    test_checksum();
    extern int test_child(void);
    test_child();
    extern int test_child_table(void);
    test_child_table();
    extern int test_cmd_line_parser(void);
    test_cmd_line_parser();
    extern int test_data(void);
    test_data();
    extern int test_dns(void);
    test_dns();
    // extern int test_dso(void);
    // test_dso();

    extern int test_ecdsa(void);
    test_ecdsa();
    
    // extern int test_flash(void);
    // test_flash();
    // extern int test_hdlc(void);
    // test_hdlc();
    extern int test_heap_array(void);
    test_heap_array();
    extern int test_heap(void);
    test_heap();
    extern int test_heap_string(void);
    test_heap_string();
    extern int test_hkdf_sha256(void);
    test_hkdf_sha256();
    extern int test_hmac_sha256(void);
    test_hmac_sha256();
    extern int test_ip6_header(void);
    test_ip6_header();
    extern int test_ip_address(void);
    test_ip_address();
    extern int test_linked_list(void);
    test_linked_list();
    // extern int test_link_quality(void);
    // test_link_quality();
    extern int test_lowpan(void);
    test_lowpan();
    extern int test_mac_frame(void);
    test_mac_frame();
    extern int test_macros(void);
    test_macros();
    extern int test_meshcop(void);
    test_meshcop();
    extern int test_message(void);
    test_message();
    extern int test_message_queue(void);
    test_message_queue();
    extern int test_multicast_listeners_table(void);
    test_multicast_listeners_table();
    extern int test_multicast_listeners_table(void);
    test_multicast_listeners_table();
    extern int test_ndproxy_table(void);
    test_ndproxy_table();
    extern int test_ndproxy_table(void);
    test_ndproxy_table();
    extern int test_netif(void);
    test_netif();
    extern int test_network_data(void);
    test_network_data();
    extern int test_network_name(void);
    test_network_name();
    extern int test_pool(void);
    test_pool();
    extern int test_priority_queue(void);
    test_priority_queue();
    extern int test_pskc(void);
    test_pskc();
    extern int test_pskc(void);
    test_pskc();
    extern int test_serial_number(void);
    test_serial_number();
    extern int test_smart_ptrs(void);
    test_smart_ptrs();
    // extern int test_spinel_buffer(void);
    // test_spinel_buffer();
    extern int test_spinel_decoder(void);
    test_spinel_decoder();
    extern int test_spinel_encoder(void);
    test_spinel_encoder();
    extern int test_string(void);
    test_string();

    // extern int test_timer(void);
    // test_timer();
    // extern int test_toolchain(void);
    // test_toolchain();
}

