
CPPFLAGS += -DLWIP_IPV4=1
CPPFLAGS += -DLWIP_DHCP=1
CPPFLAGS += -DLWIP_AUTOIP=1

CPPFLAGS += -DLWIP_IPV6=1
CPPFLAGS += -DLWIP_IPV6_DHCP6=1
CPPFLAGS += -DLWIP_IPV6_MLD=1
CPPFLAGS += -DLWIP_ND6_RDNSS_MAX_DNS_SERVERS=1
CPPFLAGS += -DMEMP_NUM_MLD6_GROUP=300
CPPFLAGS += -DLWIP_SOCKET_MAX_MEMBERSHIPS=300
CPPFLAGS += -DLWIP_MULTICAST_PING=1
CPPFLAGS += -DLWIP_NETBUF_RECVINFO=1
CPPFLAGS += -DLWIP_IPV6_SCOPES=0
CPPFLAGS += -DLWIP_IPV6_FORWARD=1
CPPFLAGS += -DLWIP_IPV6_NUM_ADDRESSES=20
CPPFLAGS += -DDEFAULT_RAW_RECVMBOX_SIZE=64
CPPFLAGS += -DMEMP_NUM_NETBUF=16
CPPFLAGS += -DLWIP_HOOK_FILENAME=\"include/otbr_lwip_hooks.h\"

CPPFLAGS += -DOPENTHREAD_CONFIG_NUM_MESSAGE_BUFFERS=256
CPPFLAGS += -DLWIP_DNS_SERVER=0
CPPFLAGS += -DOPENTHREAD_BORDER_ROUTER=1
