ifdef DISABLE_PRINT
CPPFLAGS += -DOPENTHREAD_CONFIG_LOG_OUTPUT=OPENTHREAD_CONFIG_LOG_OUTPUT_NONE
endif

CPPFLAGS += -D__int64_t_defined=1

CPPFLAGS += -DPACKAGE_NAME=\"OPENTHREAD\"
CPPFLAGS += -DPACKAGE_VERSION=\"2ce3d3bf0\"

CPPFLAGS += -DOPENTHREAD_CONFIG_MAC_SOFTWARE_ACK_TIMEOUT_ENABLE=0
CPPFLAGS += -DOPENTHREAD_CONFIG_MAC_SOFTWARE_RETRANSMIT_ENABLE=1
CPPFLAGS += -DOPENTHREAD_CONFIG_MAC_SOFTWARE_CSMA_BACKOFF_ENABLE=0
CPPFLAGS += -DOPENTHREAD_CONFIG_MAC_SOFTWARE_TX_SECURITY_ENABLE=0
CPPFLAGS += -DOPENTHREAD_CONFIG_MAC_SOFTWARE_TX_TIMING_ENABLE=0
CPPFLAGS += -DOPENTHREAD_CONFIG_MAC_SOFTWARE_ENERGY_SCAN_ENABLE=1

CPPFLAGS += -DOT_CLI_UART_LOCK_HDR_FILE=\"openthread_port.h\"

CPPFLAGS += -DOPENTHREAD_EXAMPLES_SIMULATION=0

ifdef CONFIG_OPENTHREAD_CONFIG_THREAD_VERSION
CPPFLAGS += -DOPENTHREAD_CONFIG_THREAD_VERSION=${CONFIG_OPENTHREAD_CONFIG_THREAD_VERSION}
else
CPPFLAGS += -DOPENTHREAD_CONFIG_THREAD_VERSION=4
endif
CPPFLAGS += -DOPENTHREAD_CONFIG_PLATFORM_USEC_TIMER_ENABLE=1

CPPFLAGS += -DOPENTHREAD_ENABLE_NCP_VENDOR_HOOK=0

CPPFLAGS += -DOPENTHREAD_CONFIG_LEGACY_ENABLE=0

CPPFLAGS += -DOPENTHREAD_PLATFORM_POSIX=0

CPPFLAGS += -DOPENTHREAD_POSIX=0

CPPFLAGS += -DOPENTHREAD_ENABLE_VENDOR_EXTENSION=0

CPPFLAGS += -Wimplicit-fallthrough=0 -Wno-switch-default

ifdef CONFIG_OPENTHREAD_UTILS

CPPFLAGS += -DOPENTHREAD_FTD=0
CONFIG_FTD := 0

CPPFLAGS += -DOPENTHREAD_MTD=1
OPENTHREAD_MTD := 1

CPPFLAGS += -DOPENTHREAD_RADIO=0
OPENTHREAD_RADIO := 0

CPPFLAGS += -DOPENTHREAD_CONFIG_FILE=\"include/openthread-core-bl-config.h\"

CPPFLAGS += -DOPENTHREAD_PROJECT_CORE_CONFIG_FILE=\"include/openthread-core-bl-config.h\"

CPPFLAGS += -DOPENTHREAD_CORE_CONFIG_PLATFORM_CHECK_FILE=\"include/openthread-core-bl-config-check.h\"

CPPFLAGS += -DOPENTHREAD_CONFIG_MLE_LINK_METRICS_SUBJECT_ENABLE=1
CPPFLAGS += -DOPENTHREAD_CONFIG_MLE_LINK_METRICS_INITIATOR_ENABLE=1

CPPFLAGS += -DOPENTHREAD_CONFIG_MAC_CSL_RECEIVER_ENABLE=1

CPPFLAGS += -DOPENTHREAD_CONFIG_TMF_PROXY_MLR_ENABLE=1
CPPFLAGS += -DOPENTHREAD_CONFIG_DUA_ENABLE=1
CPPFLAGS += -DOPENTHREAD_CONFIG_MLR_ENABLE=1

CPPFLAGS += -DOPENTHREAD_CONFIG_CHILD_SUPERVISION_ENABLE=1

CPPFLAGS += -DOPENTHREAD_CONFIG_IP6_FRAGMENTATION_ENABLE=1

CPPFLAGS += -DOPENTHREAD_CONFIG_TMF_NETWORK_DIAG_MTD_ENABLE=1
CPPFLAGS += -DOPENTHREAD_CONFIG_TMF_NETDATA_SERVICE_ENABLE=1
CPPFLAGS += -DOPENTHREAD_CONFIG_TMF_ANYCAST_LOCATOR_ENABLE=1
CPPFLAGS += -DOPENTHREAD_CONFIG_DATASET_UPDATER_ENABLE=1

CPPFLAGS += -DOPENTHREAD_CONFIG_COAP_BLOCKWISE_TRANSFER_ENABLE=1
CPPFLAGS += -DOPENTHREAD_CONFIG_COAP_SECURE_API_ENABLE=1

CPPFLAGS += -DOPENTHREAD_CONFIG_DHCP6_CLIENT_ENABLE=1

CPPFLAGS += -DOPENTHREAD_CONFIG_NEIGHBOR_DISCOVERY_AGENT_ENABLE=1

CPPFLAGS += -DOPENTHREAD_CONFIG_COAP_API_ENABLE=1

CPPFLAGS += -DOPENTHREAD_CONFIG_IP6_SLAAC_ENABLE=1

CPPFLAGS += -DOPENTHREAD_CONFIG_ECDSA_ENABLE=1
CPPFLAGS += -DOPENTHREAD_CONFIG_SRP_CLIENT_ENABLE=1
CPPFLAGS += -DOPENTHREAD_CONFIG_SRP_CLIENT_AUTO_START_API_ENABLE=1

CPPFLAGS += -DOPENTHREAD_CONFIG_DNS_CLIENT_ENABLE=1

CPPFLAGS += -DOPENTHREAD_CONFIG_PING_SENDER_ENABLE=1
CPPFLAGS += -DOPENTHREAD_CONFIG_SNTP_CLIENT_ENABLE=1
CPPFLAGS += -DOPENTHREAD_CONFIG_REFERENCE_DEVICE_ENABLE=1

CPPFLAGS += -DOPENTHREAD_CONFIG_SRP_SERVER_ENABLE=0

CPPFLAGS += -DOPENTHREAD_CONFIG_BORDER_ROUTER_ENABLE=0
CPPFLAGS += -DOPENTHREAD_CONFIG_BACKBONE_ROUTER_ENABLE=0

CPPFLAGS += -DOPENTHREAD_CONFIG_PLATFORM_XTAL_ACCURACY=40

CPPFLAGS += -DOPENTHREAD_CONFIG_MAC_BEACON_PAYLOAD_PARSING_ENABLE=1
CPPFLAGS += -DOPENTHREAD_CONFIG_MAC_OUTGOING_BEACON_PAYLOAD_ENABLE=1
endif

CPPFLAGS += -Dtcp_input=tcp_input_ot
CPPFLAGS += -Dtcp_output=tcp_output_ot
CPPFLAGS += -Dtcp_close=tcp_close_ot