
CPPFLAGS += -DOPENTHREAD_PROJECT_CORE_CONFIG_FILE=\"${CONFIG_OPENTHREAD_FILE}\"
CPPFLAGS += -DOPENTHREAD_CORE_CONFIG_PLATFORM_CHECK_FILE=\"${CONFIG_OPENTHREAD_CHECK_FILE}\"

ifdef OT_NCP
	ifdef OT_CLI
		$(error "OT_NCP can't be defined with OT_CLI set true.")
	endif
endif

ifdef OT_NCP
	ifeq ($(OT_NCP), 0)
		CPPFLAGS += -DOPENTHREAD_FTD=0
		CPPFLAGS += -DOPENTHREAD_MTD=0
		CPPFLAGS += -DOPENTHREAD_RADIO=1
	else
		ifeq ($(OT_FTD), 1)
			CPPFLAGS += -DOPENTHREAD_FTD=1
			CPPFLAGS += -DOPENTHREAD_MTD=0
		else
			CPPFLAGS += -DOPENTHREAD_FTD=0
			CPPFLAGS += -DOPENTHREAD_MTD=1
		endif
		CPPFLAGS += -DOPENTHREAD_RADIO=0
	endif
else
	ifndef OT_FTD
		$(info "OT_FTD is NOT defined.")
	endif
	CPPFLAGS += -DOPENTHREAD_RADIO=0
	ifeq ($(OT_FTD), 1)
		CPPFLAGS += -DOPENTHREAD_FTD=1
		CPPFLAGS += -DOPENTHREAD_MTD=0
	else
		CPPFLAGS += -DOPENTHREAD_FTD=0
		CPPFLAGS += -DOPENTHREAD_MTD=1
	endif
endif
