ifdef DISABLE_PRINT
CPPFLAGS += -DOPENTHREAD_CONFIG_LOG_OUTPUT=OPENTHREAD_CONFIG_LOG_OUTPUT_NONE
endif

CPPFLAGS += -D__int64_t_defined=1

CPPFLAGS += -DPACKAGE_NAME=\"OPENTHREAD\"
CPPFLAGS += -DPACKAGE_VERSION=\"c6179c24e\"

CPPFLAGS += -DOPENTHREAD_CONFIG_MAC_SOFTWARE_ACK_TIMEOUT_ENABLE=0
CPPFLAGS += -DOPENTHREAD_CONFIG_MAC_SOFTWARE_RETRANSMIT_ENABLE=1
CPPFLAGS += -DOPENTHREAD_CONFIG_MAC_SOFTWARE_CSMA_BACKOFF_ENABLE=0
CPPFLAGS += -DOPENTHREAD_CONFIG_MAC_SOFTWARE_TX_SECURITY_ENABLE=0
CPPFLAGS += -DOPENTHREAD_CONFIG_MAC_SOFTWARE_TX_TIMING_ENABLE=0
CPPFLAGS += -DOPENTHREAD_CONFIG_MAC_SOFTWARE_ENERGY_SCAN_ENABLE=1

CPPFLAGS += -DOT_CLI_UART_LOCK_HDR_FILE=\"openthread_port.h\"

CPPFLAGS += -DOPENTHREAD_EXAMPLES_SIMULATION=0

CPPFLAGS += -DOPENTHREAD_CONFIG_THREAD_VERSION=${CONFIG_OPENTHREAD_CONFIG_THREAD_VERSION}

CPPFLAGS += -DOPENTHREAD_ENABLE_NCP_VENDOR_HOOK=0

CPPFLAGS += -DOPENTHREAD_CONFIG_LEGACY_ENABLE=0

CPPFLAGS += -DOPENTHREAD_PLATFORM_POSIX=0

CPPFLAGS += -DOPENTHREAD_POSIX=0

CPPFLAGS += -DOPENTHREAD_ENABLE_VENDOR_EXTENSION=0

CPPFLAGS += -Wimplicit-fallthrough=0 -Wno-switch-default

CPPFLAGS += -DOPENTHREAD_CONFIG_PLATFORM_INFO=\"${CONFIG_CHIP_NAME}\"

CPPFLAGS += -DOPENTHREAD_CONFIG_HEAP_EXTERNAL_ENABLE=1

CPPFLAGS += -DOPENTHREAD_CONFIG_LOG_SUFFIX=\"\\r\\n\"

ifeq ($(origin CONFIG_NCP), undefined)
    CPPFLAGS += -DOPENTHREAD_RADIO=$(OPENTHREAD_RADIO)

    ifeq ($(CONFIG_FTD), 1)
        CPPFLAGS += -DOPENTHREAD_FTD=1
        CPPFLAGS += -DOPENTHREAD_MTD=0
    else
        CPPFLAGS += -DOPENTHREAD_FTD=0
        CPPFLAGS += -DOPENTHREAD_MTD=1

        CPPFLAGS += -DCONFIG_PP=${CONFIG_PP}
    endif

    CPPFLAGS += -DCONFIG_PREFIX=${CONFIG_PREFIX}

    ifeq ($(origin CONFIG_OTDEMO), undefined)
        #only cli command image
        ifeq ($(CONFIG_FTD), 1)
            # only build image with joiner and commissioner configuration for FTD device
            CPPFLAGS += -DOPENTHREAD_CONFIG_COMMISSIONER_ENABLE=1
            CPPFLAGS += -DOPENTHREAD_CONFIG_JOINER_ENABLE=1
        else
            # only build image with joiner configuration for MTD device
            CPPFLAGS += -DOPENTHREAD_CONFIG_JOINER_ENABLE=1
        endif
    else
        CPPFLAGS += -DCONFIG_OTDEMO=${CONFIG_OTDEMO}
        ifeq (${CONFIG_OTDEMO}, 2)
            # coap demo image
            CPPFLAGS += -DOPENTHREAD_CONFIG_COAP_API_ENABLE=1
        endif
    endif
else
    CPPFLAGS += -DDISABLE_PRINT
    CPPFLAGS += -DCONFIG_NCP=${CONFIG_NCP}
    CPPFLAGS += -DOPENTHREAD_CONFIG_NCP_HDLC_ENABLE=1
    CPPFLAGS += -DOPENTHREAD_ENABLE_NCP_SPINEL_ENCRYPTER=0

    ifeq ($(CONFIG_NCP), 0)
        CPPFLAGS += -DOPENTHREAD_RADIO=$(OPENTHREAD_RADIO)
        CPPFLAGS += -DOPENTHREAD_SPINEL_CONFIG_OPENTHREAD_MESSAGE_ENABLE=0
        CPPFLAGS += -DOPENTHREAD_FTD=0
        CPPFLAGS += -DOPENTHREAD_MTD=0
    else
        CPPFLAGS += -DOPENTHREAD_RADIO=$(OPENTHREAD_RADIO)
        CPPFLAGS += -DOPENTHREAD_SPINEL_CONFIG_OPENTHREAD_MESSAGE_ENABLE=1
        ifeq ($(CONFIG_FTD), 1)
            CPPFLAGS += -DOPENTHREAD_FTD=1
            CPPFLAGS += -DOPENTHREAD_MTD=0
        else
            CPPFLAGS += -DOPENTHREAD_FTD=0
            CPPFLAGS += -DOPENTHREAD_MTD=1
        endif
    endif
endif

CPPFLAGS += -DOPENTHREAD_CONFIG_PLATFORM_USEC_TIMER_ENABLE=1

ifeq ($(CONFIG_TIMESYNC), 1)
CPPFLAGS += -DOPENTHREAD_CONFIG_TIME_SYNC_ENABLE=1
endif

ifneq ($(CONFIG_OPENTHREAD_CONFIG_THREAD_VERSION), 2)
ifeq ($(CONFIG_LINK_METRICS), 1)
CPPFLAGS += -DOPENTHREAD_CONFIG_MLE_LINK_METRICS_SUBJECT_ENABLE=1
CPPFLAGS += -DOPENTHREAD_CONFIG_MLE_LINK_METRICS_INITIATOR_ENABLE=1
else
CPPFLAGS += -DOPENTHREAD_CONFIG_MLE_LINK_METRICS_SUBJECT_ENABLE=0
endif

ifeq ($(CONFIG_CSL_RX), 1)
CPPFLAGS += -DOPENTHREAD_CONFIG_MAC_CSL_RECEIVER_ENABLE=1
endif
endif

ifeq ($(CONFIG_GOLDEN_UNIT), 1)
CPPFLAGS += -DOPENTHREAD_CONFIG_REFERENCE_DEVICE_ENABLE=1
CPPFLAGS += -DOPENTHREAD_CONFIG_MAC_FILTER_ENABLE=1
endif

ifneq ($(CONFIG_OPENTHREAD_CONFIG_THREAD_VERSION), 2)
CPPFLAGS += -DOPENTHREAD_CONFIG_TMF_PROXY_MLR_ENABLE=1
CPPFLAGS += -DOPENTHREAD_CONFIG_DUA_ENABLE=1
CPPFLAGS += -DOPENTHREAD_CONFIG_MLR_ENABLE=1
endif

CPPFLAGS += -DOPENTHREAD_CONFIG_CHILD_SUPERVISION_ENABLE=1

CPPFLAGS += -DOPENTHREAD_CONFIG_IP6_FRAGMENTATION_ENABLE=1

CPPFLAGS += -DOPENTHREAD_CONFIG_TMF_NETWORK_DIAG_MTD_ENABLE=1
CPPFLAGS += -DOPENTHREAD_CONFIG_TMF_NETDATA_SERVICE_ENABLE=1
CPPFLAGS += -DOPENTHREAD_CONFIG_TMF_ANYCAST_LOCATOR_ENABLE=1
CPPFLAGS += -DOPENTHREAD_CONFIG_DATASET_UPDATER_ENABLE=1

CPPFLAGS += -DOPENTHREAD_CONFIG_COAP_BLOCKWISE_TRANSFER_ENABLE=1
CPPFLAGS += -DOPENTHREAD_CONFIG_COAP_SECURE_API_ENABLE=1

CPPFLAGS += -DOPENTHREAD_CONFIG_DHCP6_CLIENT_ENABLE=1

CPPFLAGS += -DOPENTHREAD_CONFIG_NEIGHBOR_DISCOVERY_AGENT_ENABLE=1

CPPFLAGS += -DOPENTHREAD_CONFIG_COAP_API_ENABLE=1

CPPFLAGS += -DOPENTHREAD_CONFIG_IP6_SLAAC_ENABLE=1

CPPFLAGS += -DOPENTHREAD_CONFIG_ECDSA_ENABLE=1
CPPFLAGS += -DOPENTHREAD_CONFIG_SRP_CLIENT_ENABLE=1
CPPFLAGS += -DOPENTHREAD_CONFIG_SRP_CLIENT_AUTO_START_API_ENABLE=1

CPPFLAGS += -DOPENTHREAD_CONFIG_DNS_CLIENT_ENABLE=1

CPPFLAGS += -DOPENTHREAD_CONFIG_PING_SENDER_ENABLE=1
CPPFLAGS += -DOPENTHREAD_CONFIG_SNTP_CLIENT_ENABLE=1

CPPFLAGS += -DOPENTHREAD_CONFIG_PLATFORM_XTAL_ACCURACY=40

CPPFLAGS += -DOPENTHREAD_CONFIG_MAC_BEACON_PAYLOAD_PARSING_ENABLE=1
CPPFLAGS += -DOPENTHREAD_CONFIG_MAC_OUTGOING_BEACON_PAYLOAD_ENABLE=1

CPPFLAGS += -DOPENTHREAD_CONFIG_FILE=\"include/openthread-core-bl-config.h\"
CPPFLAGS += -DOPENTHREAD_PROJECT_CORE_CONFIG_FILE=\"include/openthread-core-bl-config.h\"
CPPFLAGS += -DOPENTHREAD_CORE_CONFIG_PLATFORM_CHECK_FILE=\"include/openthread-core-bl-config-check.h\"

ifeq ($(CONFIG_OTBR), 1)
CPPFLAGS += -DOPENTHREAD_CONFIG_TMF_NETDATA_SERVICE_ENABLE=1
CPPFLAGS += -DOPENTHREAD_CONFIG_SRP_SERVER_ENABLE=1
CPPFLAGS += -DOPENTHREAD_CONFIG_BORDER_ROUTER_ENABLE=1
CPPFLAGS += -DOPENTHREAD_CONFIG_BORDER_ROUTING_ENABLE=1
CPPFLAGS += -DOPENTHREAD_CONFIG_BACKBONE_ROUTER_ENABLE=1
CPPFLAGS += -DOPENTHREAD_CONFIG_BORDER_AGENT_ENABLE=1
CPPFLAGS += -DOPENTHREAD_CONFIG_DNSSD_SERVER_ENABLE=1
CPPFLAGS += -DOPENTHREAD_CONFIG_PLATFORM_UDP_ENABLE=1
else
CPPFLAGS += -DOPENTHREAD_CONFIG_SRP_SERVER_ENABLE=0
CPPFLAGS += -DOPENTHREAD_CONFIG_BORDER_ROUTER_ENABLE=0
CPPFLAGS += -DOPENTHREAD_CONFIG_BACKBONE_ROUTER_ENABLE=0
endif
